quokka clean

diff --git a/scripts/bash/quokka b/scripts/bash/quokka
--- a/scripts/bash/quokka
+++ b/scripts/bash/quokka
@@ -10,6 +10,7 @@ Usage:
   quokka run <preset> <problem> [--input <file>] [--fpe] [--root <path>]
   quokka list <preset> [--root <path>]
   quokka target <preset> [--root <path>]
+  quokka clean [--root <path>]
 
 Presets:
   1d
@@ -21,7 +22,7 @@ EOF
 
 RED='\033[0;31m'
 GREEN='\033[0;32m'
-CYAN='\033[0;36m'
+MAGENTA='\033[0;35m'
 BOLD='\033[1m'
 RESET='\033[0m'
 
@@ -31,7 +32,7 @@ die() {
 }
 
 log_cmd() {
-	echo -e "${CYAN}+ $*${RESET}"
+	echo -e "${MAGENTA}+ $*${RESET}"
 }
 
 require_arg() {
@@ -116,6 +117,15 @@ list_problems() {
 	find "${ROOT}/src/problems" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort
 }
 
+clean_tests() {
+	local tests_dir="${ROOT}/tests"
+	[ -d "$tests_dir" ] || die "tests directory not found: ${tests_dir} (use --root to specify the quokka root)"
+	log_cmd "cd ${tests_dir} && rm -rf plt* slice* chk* part_* *.csv *.pdf *.png Backtrace.*"
+	cd "$tests_dir"
+	rm -rf plt* slice* chk* part_*
+	rm -f ./*.csv ./*.pdf ./*.png Backtrace.*
+}
+
 show_targets() {
 	log_cmd "cmake --build ${BUILD_DIR} --target help"
 	cmake --build "$BUILD_DIR" --target help
@@ -176,9 +186,8 @@ while [ "$#" -gt 0 ]; do
 	esac
 done
 
-[ -n "$PRESET" ] || die "missing preset"
 resolve_root "$ROOT"
-parse_preset "$PRESET"
+[ "$COMMAND" = clean ] || { [ -n "$PRESET" ] || die "missing preset"; parse_preset "$PRESET"; }
 
 case "$COMMAND" in
 config)
@@ -229,6 +238,12 @@ target)
 	[ -z "$INPUT_FILE" ] || die "target does not accept --input"
 	[ "$ENABLE_FPE" -eq 0 ] || die "target does not accept --fpe"
 	show_targets
+	;;
+clean)
+	[ -z "$PROBLEM" ] || die "clean does not take a problem name"
+	[ -z "$INPUT_FILE" ] || die "clean does not accept --input"
+	[ "$ENABLE_FPE" -eq 0 ] || die "clean does not accept --fpe"
+	clean_tests
 	;;
 *)
 	die "unknown command '${COMMAND}'"
